-- ============================================================================
-- WCAG Success Criteria Conditions - Complete Checklist
-- Generated from checks.json
-- Total Conditions: 516
-- ============================================================================

-- Clean up existing data
TRUNCATE TABLE findings, page_sc_results, webcomply_report_summary, page_audits, compliance_scores, pages, reference_sc_conditions RESTART IDENTITY CASCADE;

-- Insert all WCAG conditions
INSERT INTO reference_sc_conditions (sc_id, condition_text, condition_type, axe_rule_id, default_checked) VALUES
  ('1.1.1', 'Images have alternative text where required (non-decorative images).', 'axe-core', 'image-alt', true),
  ('1.1.1', 'Decorative images are marked with empty alternative text (alt="") or implemented as CSS backgrounds.', 'axe-core', 'image-alt', true),
  ('1.1.1', 'Linked images have descriptive and meaningful alternative text.', 'manual', NULL, false),
  ('1.1.1', 'Equivalent text alternatives for complex images are provided in context or via a separate linked page.', 'manual', NULL, false),
  ('1.1.1', 'Form buttons have descriptive values that convey their purpose.', 'manual', NULL, false),
  ('1.1.1', 'Inputs have appropriate accessible names.', 'manual', NULL, false),
  ('1.1.1', 'Embedded multimedia is identified using accessible text alternatives.', 'manual', NULL, false),
  ('1.1.1', 'Frames and iframes have appropriate and descriptive titles.', 'manual', NULL, false),
  ('1.1.1', 'Embedded objects (such as <object> elements) that convey information have accessible text alternatives.', 'axe-core', 'object-alt', true),
  ('1.1.1', 'Embedded objects include fallback text or accessible naming mechanisms when required.', 'axe-core', 'object-alt', true),
  ('1.1.1', 'Images have appropriate and equivalent alternative text.', 'manual', NULL, false),
  ('1.1.1', 'Embedded multimedia is identified using accessible text alternatives beyond object fallback.', 'manual', NULL, false),
  ('1.1.1', 'SVG elements that convey information and are exposed as images have accessible text alternatives.', 'axe-core', 'svg-img-alt', true),
  ('1.1.1', 'SVG images include appropriate accessible names via <title>, <desc>, or aria-label where required.', 'axe-core', 'svg-img-alt', true),
  ('1.1.1', 'Raster images and other non-SVG images have appropriate and equivalent alternative text.', 'manual', NULL, false),
  ('1.1.1', 'Elements with role="img" that convey information have accessible text alternatives.', 'axe-core', 'role-img-alt', true),
  ('1.1.1', 'Elements with role="img" include appropriate accessible names via aria-label, aria-labelledby, or equivalent mechanisms.', 'axe-core', 'role-img-alt', true),
  ('1.1.1', 'Raster images and other non-role="img" images have appropriate and equivalent alternative text.', 'manual', NULL, false),
  ('1.1.1', 'Input elements of type="image" that convey information or functionality have accessible text alternatives.', 'axe-core', 'input-image-alt', true),
  ('1.1.1', 'Image input controls include appropriate accessible names via alt text or equivalent mechanisms.', 'axe-core', 'input-image-alt', true),
  ('1.1.1', 'Non-input images have appropriate and equivalent alternative text.', 'manual', NULL, false),
  ('1.1.1', 'Form buttons have descriptive values that convey their purpose beyond image inputs.', 'manual', NULL, false),
  ('1.1.1', 'Inputs (other than image inputs) have appropriate accessible names.', 'manual', NULL, false),
  ('1.1.1', 'Elements with role="meter" have an accessible name that identifies the non-text content.', 'axe-core', 'aria-meter-name', true),
  ('1.1.1', 'Inputs (other than role="meter") have appropriate accessible names.', 'manual', NULL, false),
  ('1.1.1', 'Elements with role="progressbar" have an accessible name that identifies the non-text content.', 'axe-core', 'aria-progressbar-name', true),
  ('1.1.1', 'Inputs (other than role="progressbar") have appropriate accessible names.', 'manual', NULL, false),
  ('1.2.1', 'Audio-only media elements include a mechanism (such as a track or accessible reference) indicating the presence of a transcript or caption alternative.', 'axe-core', NULL, true),
  ('1.2.1', 'A complete and accurate transcript is provided for all non-live audio-only content.', 'manual', NULL, false),
  ('1.2.1', 'The transcript includes all relevant spoken dialogue and meaningful sounds.', 'manual', NULL, false),
  ('1.2.1', 'For non-live video-only content, a descriptive transcript or audio description is provided.', 'manual', NULL, false),
  ('1.2.1', 'Decorative video-only content is correctly identified and does not require a transcript.', 'manual', NULL, false),
  ('1.2.1', 'Transcripts or audio descriptions are easy to locate and accessible to users.', 'manual', NULL, false),
  ('1.2.1', 'The transcript or audio description accurately reflects the timing and meaning of the media content.', 'manual', NULL, false),
  ('1.2.2', 'Prerecorded video elements include a captions track (<track kind="captions">) associated with the video.', 'axe-core', 'video-caption', true),
  ('1.2.2', 'Captions are synchronized accurately with the audio.', 'manual', NULL, false),
  ('1.2.2', 'Captions include all spoken dialogue and relevant non-speech audio (e.g., sound effects).', 'manual', NULL, false),
  ('1.2.2', 'Captions are complete for the entire duration of the prerecorded video.', 'manual', NULL, false),
  ('1.2.3', 'A descriptive transcript or audio description is provided for non-live video.', 'manual', NULL, false),
  ('1.2.3', 'NOTE: Only required if there is relevant visual content that is not presented in the audio.', 'manual', NULL, false),
  ('1.2.4', 'Synchronized captions are provided for live media that contains audio (audio-only broadcasts, web casts, video conferences, etc.)', 'manual', NULL, false),
  ('1.2.5', 'Audio descriptions are provided for non-live video.', 'manual', NULL, false),
  ('1.2.5', 'NOTE: Only required if there is relevant visual content that is not presented in the audio.', 'manual', NULL, false),
  ('1.2.5', 'While not required at Level AA, for optimal accessibility WebAIM recommends descriptive transcripts in addition to audio descriptions.', 'manual', NULL, false),
  ('1.2.6', 'A sign language video is provided for media that contains audio', 'manual', NULL, false),
  ('1.2.7', 'When audio description cannot be added to video due to insufficient pauses in the audio, an alternative version of the', 'manual', NULL, false),
  ('1.2.7', 'video with pauses that allow audio descriptions is provided.', 'manual', NULL, false),
  ('1.2.8', 'A descriptive transcript is provided for pre-recorded media that has a video track. For optimal accessibility, WebAIM', 'manual', NULL, false),
  ('1.2.8', 'strongly recommends transcripts for all multimedia.', 'manual', NULL, false),
  ('1.2.9', 'A descriptive text transcript (e.g., the script of the live audio) is provided for live content that has audio.', 'manual', NULL, false),
  ('1.3.1', 'ARIA parent roles that require specific child roles contain all required child elements (for example, role="list" contains role="listitem").', 'axe-core', 'aria-required-children', true),
  ('1.3.1', 'Headings, landmarks, lists, and other structural elements are marked up using correct native HTML semantics.', 'manual', NULL, false),
  ('1.3.1', 'Lists are implemented using appropriate HTML elements (ul, ol, dl) or correct ARIA roles where HTML is insufficient.', 'manual', NULL, false),
  ('1.3.1', 'Tables are used only for tabular data and not for layout purposes.', 'manual', NULL, false),
  ('1.3.1', 'Data table headers are correctly associated with their corresponding data cells.', 'manual', NULL, false),
  ('1.3.1', 'Data tables include captions when needed and captions are correctly associated with the tables.', 'manual', NULL, false),
  ('1.3.1', 'Form inputs have visible and programmatically associated text labels.', 'manual', NULL, false),
  ('1.3.1', 'Related form controls are grouped using fieldset and legend where appropriate.', 'manual', NULL, false),
  ('1.3.1', 'ARIA labelling is used correctly only when native HTML semantics are insufficient.', 'manual', NULL, false),
  ('1.3.1', 'The document body (<body>) is not hidden from assistive technologies using aria-hidden="true".', 'axe-core', 'aria-hidden-body', true),
  ('1.3.1', 'Semantic markup is appropriately used to designate headings, regions/landmarks, lists, and emphasized or special text.', 'manual', NULL, false),
  ('1.3.1', 'Tables are used only for tabular data and data cells are correctly associated with their headers.', 'manual', NULL, false),
  ('1.3.1', 'Data table captions, when present, are correctly associated with the corresponding data tables.', 'manual', NULL, false),
  ('1.3.1', 'Text labels are programmatically associated with form inputs.', 'manual', NULL, false),
  ('1.3.1', 'ARIA child roles that require a specific parent role are contained within the correct required parent elements (for example, role="listitem" is contained within role="list").', 'axe-core', 'aria-required-parent', true),
  ('1.3.1', 'Data table captions, when present, are correctly associated with the data tables.', 'manual', NULL, false),
  ('1.3.1', 'Definition lists use correct semantic structure where <dl> elements contain only <dt> and <dd> elements as direct children.', 'axe-core', 'definition-list', true),
  ('1.3.1', 'Lists (ordered, unordered, and definition lists) are used appropriately to represent related content.', 'manual', NULL, false),
  ('1.3.1', 'Definition list items (<dt> and <dd>) are contained within a <dl> element and not used outside of a definition list.', 'axe-core', 'dlitem', true),
  ('1.3.1', 'Content that is visually presented as a list is marked up using correct list semantics (ul, ol, or role="list").', 'axe-core', 'list', true),
  ('1.3.1', 'List items are contained within a valid list structure (li or role="listitem").', 'axe-core', 'list', true),
  ('1.3.1', 'Semantic markup is appropriately used to designate headings, regions/landmarks, and emphasized or special text.', 'manual', NULL, false),
  ('1.3.1', 'Lists are used appropriately to represent related content and logical groupings.', 'manual', NULL, false),
  ('1.3.1', 'List items are contained within a valid list structure (ul, ol, menu, or role="list") and are not used outside of lists.', 'axe-core', 'listitem', true),
  ('1.3.1', 'Data table cells (<td>) that use the headers attribute reference valid and existing table header cells (<th>).', 'axe-core', 'td-headers-attr', true),
  ('1.3.1', 'Data table headers are correctly identified using <th> elements.', 'manual', NULL, false),
  ('1.3.1', 'Header and data cell relationships are appropriate and meaningful for the table structure.', 'manual', NULL, false),
  ('1.3.1', 'Table header cells (<th>) are associated with at least one data cell (<td>) within the same table.', 'axe-core', 'th-has-data-cells', true),
  ('1.3.1', 'Header and data cell relationships are correct and meaningful for the table structure.', 'manual', NULL, false),
  ('1.3.2', 'The reading and navigation order (determined by code order) is logical and intuitive', 'manual', NULL, false),
  ('1.3.3', 'Instructions do not rely upon shape, size, or visual location (e.g., "Click the square icon to continue" or "Instructions are in the right-hand column").', 'manual', NULL, false),
  ('1.3.3', 'Instructions do not rely upon sound (e.g., "A beeping sound indicates you may continue.")', 'manual', NULL, false),
  ('1.3.4', 'Orientation of web content is not restricted to only portrait or landscape, unless a specific orientation is necessary.', 'manual', NULL, false),
  ('1.3.5', 'Form input fields that support autocomplete use valid and appropriate autocomplete attribute values as defined by the HTML specification.', 'axe-core', 'autocomplete-valid', true),
  ('1.3.5', 'The selected autocomplete values accurately reflect the intended purpose of each input field (e.g., name, email, address).', 'manual', NULL, false),
  ('1.3.5', 'Autocomplete attributes are applied to all relevant user data fields where applicable.', 'manual', NULL, false),
  ('1.3.5', 'Inputs that should not have autocomplete do not include inappropriate autocomplete values.', 'manual', NULL, false),
  ('1.3.6', 'Regions/landmarks are used to identify page regions.', 'manual', NULL, false),
  ('1.3.6', 'ARIA is used, where appropriate, to enhance HTML semantics to better identify the purpose of interface components.', 'manual', NULL, false),
  ('1.4.1', 'Links within blocks of text are visually distinguishable from surrounding text without relying on color alone.', 'axe-core', 'link-in-text-block', true),
  ('1.4.1', 'Color is not used as the sole method to convey information, indicate status, prompt action, or distinguish visual elements other than links.', 'manual', NULL, false),
  ('1.4.1', 'Non-link visual cues (icons, charts, error messages, required fields, instructions) do not rely on color alone.', 'manual', NULL, false),
  ('1.4.1', 'The contrast ratio between link text and surrounding text is at least 3:1 when color is used to distinguish links.', 'manual', NULL, false),
  ('1.4.1', 'Links provide an additional visual indicator (such as underline) on hover and keyboard focus.', 'manual', NULL, false),
  ('1.4.1', 'Visual distinctions conveyed by color are also available programmatically or through text alternatives.', 'manual', NULL, false),
  ('1.4.2', 'Audio does not automatically play for more than 3 seconds without a user-controlled mechanism to stop or pause it.', 'axe-core', 'no-autoplay-audio', true),
  ('1.4.2', 'A visible and operable control is available to pause, stop, or mute the audio.', 'manual', NULL, false),
  ('1.4.2', 'Audio controls are keyboard accessible.', 'manual', NULL, false),
  ('1.4.2', 'Users can independently adjust audio volume without affecting system volume.', 'manual', NULL, false),
  ('1.4.2', 'Audio control mechanisms are clearly labeled and understandable.', 'manual', NULL, false),
  ('1.4.3', 'Text and images of text meet the minimum contrast ratio of 4.5:1 for normal text.', 'axe-core', 'color-contrast', true),
  ('1.4.3', 'Large-scale text meets the minimum contrast ratio of 3:1.', 'axe-core', 'color-contrast', true),
  ('1.4.3', 'Text that is part of images is essential and cannot be presented using real text.', 'manual', NULL, false),
  ('1.4.3', 'Contrast is evaluated correctly for text rendered over gradients, images, patterns, or videos.', 'manual', NULL, false),
  ('1.4.3', 'Custom fonts, font weights, and font rendering do not reduce effective contrast below minimum thresholds.', 'manual', NULL, false),
  ('1.4.3', 'Text contrast remains sufficient in all interaction states (hover, focus, active, visited).', 'manual', NULL, false),
  ('1.4.3', 'Contrast is maintained when user styles, zoom, or high-contrast modes are applied.', 'manual', NULL, false),
  ('1.4.4', 'The viewport meta tag does not restrict user scaling (e.g., does not disable zoom or set maximum-scale less than 2).', 'axe-core', 'meta-viewport', true),
  ('1.4.4', 'Text content remains readable and does not become truncated, overlapped, or clipped when zoomed to 200%.', 'manual', NULL, false),
  ('1.4.4', 'All functionality remains available and operable when the page is zoomed to 200%.', 'manual', NULL, false),
  ('1.4.4', 'Horizontal scrolling is not required for reading blocks of text at 200% zoom (except where allowed).', 'manual', NULL, false),
  ('1.4.4', 'Fixed-position or absolutely positioned content does not obscure text or controls when zoomed.', 'manual', NULL, false),
  ('1.4.4', 'Interactive elements remain visible, usable, and discoverable at 200% zoom.', 'manual', NULL, false),
  ('1.4.5', 'If the same visual presentation can be made using text alone, an image is not used to present that text.', 'manual', NULL, false),
  ('1.4.6', 'Text and images of text meet the enhanced minimum color contrast ratios of 7:1 for normal text and 4.5:1 for large or bold text based on computed foreground and background colors.', 'axe-core', 'color-contrast-enhanced', true),
  ('1.4.6', 'Contrast is sufficient in all user states, including hover, focus, active, disabled, and visited states.', 'manual', NULL, false),
  ('1.4.6', 'Text displayed over images, gradients, patterns, or video maintains the required enhanced contrast ratios.', 'manual', NULL, false),
  ('1.4.6', 'Contrast remains sufficient when custom user styles, zoom, or high-contrast modes are applied.', 'manual', NULL, false),
  ('1.4.6', 'Images of text that contain meaningful content meet the enhanced contrast requirements.', 'manual', NULL, false),
  ('1.4.6', 'Dynamically updated text content maintains enhanced contrast at all times.', 'manual', NULL, false),
  ('1.4.6', 'Essential visual information conveyed through text is not lost due to insufficient contrast in real-world viewing conditions.', 'manual', NULL, false),
  ('1.4.7', 'Audio with speech has no or very low background noise so the speech is easily distinguished.', 'manual', NULL, false),
  ('1.4.8', 'Blocks of text over one sentence in length:', 'manual', NULL, false),
  ('1.4.8', 'Are no more than 80 characters wide.', 'manual', NULL, false),
  ('1.4.8', 'Are NOT fully justified (aligned to both the left and the right margins).', 'manual', NULL, false),
  ('1.4.8', 'Have adequate line spacing (at least 1/2 the height of the text) and paragraph spacing (1.5 times line spacing).', 'manual', NULL, false),
  ('1.4.8', 'Have defined or inherited foreground and background colors.', 'manual', NULL, false),
  ('1.4.8', 'Do NOT require horizontal scrolling when the text size is doubled.', 'manual', NULL, false),
  ('1.4.9', 'Images that appear to contain text are programmatically detected and flagged for review.', 'axe-core', 'image-text', true),
  ('1.4.9', 'Images containing text are used only for decorative purposes and do not convey essential information.', 'manual', NULL, false),
  ('1.4.9', 'When images of text convey information, the information cannot be presented using real text alone.', 'manual', NULL, false),
  ('1.4.9', 'Decorative images of text are appropriately marked so they are ignored by assistive technologies.', 'manual', NULL, false),
  ('1.4.9', 'Logos, branding, and other allowed exceptions are correctly identified and applied.', 'manual', NULL, false),
  ('1.4.10', 'No loss of content or functionality occurs, and horizontal scrolling is avoided when content is presented at a width of', 'manual', NULL, false),
  ('1.4.10', '320 pixels.', 'manual', NULL, false),
  ('1.4.10', 'This requires responsive design for most web sites. This is best tested by setting the browser window to 1280', 'manual', NULL, false),
  ('1.4.10', 'pixels wide and then zooming the page content to 400%.', 'manual', NULL, false),
  ('1.4.10', 'Content that requires horizontal scrolling, such as data tables, complex images (such as maps and charts), toolbars, etc. are exempted.', 'manual', NULL, false),
  ('1.4.11', 'A contrast ratio of at least 3:1 is present for differentiating graphical objects (such as icons and components of charts or graphs) and author-customized interface components (such as buttons, form controls, and focus', 'manual', NULL, false),
 
  ('1.4.11', 'indicators/outlines).', 'manual', NULL, false),
  ('1.4.11', 'At least 3:1 contrast is maintained in the various states (focus, hover, active, etc.) of author-customized interactive', 'manual', NULL, false),
  ('1.4.11', 'components.', 'manual', NULL, false),
  ('1.4.12', 'Inline styles do not set fixed line-height, letter-spacing, or word-spacing values that would prevent user text spacing adjustments.', 'axe-core', 'avoid-inline-spacing', true),
  ('1.4.12', 'Content remains readable and no text is clipped, overlapped, or truncated when paragraph, line, word, and letter spacing are increased to the specified values.', 'manual', NULL, false),
  ('1.4.12', 'All functionality remains available and operable when text spacing is adjusted.', 'manual', NULL, false),
  ('1.4.12', 'Fixed heights or containers do not cause loss of content when spacing is increased.', 'manual', NULL, false),
  ('1.4.12', 'Text spacing adjustments do not require horizontal scrolling to read blocks of text.', 'manual', NULL, false),
  ('1.4.12', 'Spacing adaptations work consistently across different browsers and assistive technologies.', 'manual', NULL, false),
  ('1.4.13', 'When additional content is presented on hover or keyboard focus:', 'manual', NULL, false),
  ('1.4.13', 'The newly revealed content can be dismissed (generally via the Esc key) without moving the pointer or keyboard', 'manual', NULL, false),
  ('1.4.13', 'focus, unless the content presents an input error or does not obscure or interfere with other page content.', 'manual', NULL, false),
  ('1.4.13', 'The pointer can be moved to the new content without the content disappearing.', 'manual', NULL, false),
  ('1.4.13', 'The new content must remain visible until the pointer or keyboard focus is moved away from the triggering', 'manual', NULL, false),
  ('1.4.13', 'control, the new content is dismissed, or the new content is no longer relevant.', 'manual', NULL, false),
  ('2.1.1', 'Scrollable regions that contain keyboard-operable content are focusable using the keyboard.', 'axe-core', 'scrollable-region-focusable', true),
  ('2.1.1', 'All interactive elements and functionality on the page can be operated using the keyboard alone.', 'manual', NULL, false),
  ('2.1.1', 'No functionality requires mouse-only, touch-only, or pointer-specific interactions.', 'manual', NULL, false),
  ('2.1.1', 'Keyboard focus order allows users to reach and operate all interactive components.', 'manual', NULL, false),
  ('2.1.1', 'Page-defined shortcut keys and accesskeys do not conflict with browser or assistive technology shortcuts.', 'manual', NULL, false),
  ('2.1.1', 'Keyboard interactions are consistent and do not trap users within components.', 'manual', NULL, false),
  ('2.1.1', 'Iframes that contain interactive or focusable elements are focusable using the keyboard.', 'axe-core', 'frame-focusable-content', true),
  ('2.1.1', 'All page functionality is available using the keyboard alone without requiring mouse or touch input.', 'manual', NULL, false),
  ('2.1.1', 'Keyboard users can reach and operate all interactive elements within frames and iframes.', 'manual', NULL, false),
  ('2.1.1', 'Keyboard focus order is logical and predictable across the main page and embedded frames.', 'manual', NULL, false),
  ('2.1.1', 'No keyboard traps exist within frames or embedded content.', 'manual', NULL, false),
  ('2.1.1', 'Server-side image maps are not used, as they are not operable using the keyboard.', 'axe-core', 'server-side-image-map', true),
  ('2.1.1', 'All page functionality is available using the keyboard alone without requiring mouse or pointer input.', 'manual', NULL, false),
  ('2.1.1', 'Client-side image maps, if used, are fully keyboard operable and accessible.', 'manual', NULL, false),
  ('2.1.1', 'Interactive regions within images can be reached and activated using the keyboard.', 'manual', NULL, false),
  ('2.1.1', 'Keyboard focus order allows users to access all interactive elements.', 'manual', NULL, false),
  ('2.1.2', 'Keyboard focus is never locked or trapped at one particular page element. The user can navigate to and from all navigable page elements using only a keyboard.', 'manual', NULL, false),
  ('2.1.3', 'Scrollable regions are keyboard focusable so users can scroll and interact with the content using only the keyboard.', 'axe-core', 'scrollable-region-focusable', true),
  ('2.1.3', 'All interactive functionality on the page can be operated using only the keyboard.', 'manual', NULL, false),
  ('2.1.3', 'Keyboard users can access and operate custom widgets and components.', 'manual', NULL, false),
  ('2.1.3', 'Keyboard focus order is logical and intuitive throughout the page.', 'manual', NULL, false),
  ('2.1.3', 'Keyboard traps are not present and users can move focus away from all components.', 'manual', NULL, false),
  ('2.1.3', 'All keyboard interactions work consistently across browsers and assistive technologies.', 'manual', NULL, false),
  ('2.1.3', 'Time-based or gesture-based interactions have equivalent keyboard alternatives.', 'manual', NULL, false),
  ('2.1.4', 'If a keyboard shortcut uses printable character keys, then the user must be able to disable the key command, change the defined key to a non-printable key (Ctrl, Alt, etc.), or only activate the shortcut when an associated interface component or button is focused.', 'manual', NULL, false),
  ('2.2.1', 'Pages do not use automatic meta refresh mechanisms that refresh or redirect the page without user control.', 'axe-core', 'meta-refresh', true),
  ('2.2.1', 'Time limits imposed by scripts, sessions, or applications provide a user-controlled mechanism to turn off, adjust, or extend the time limit.', 'manual', NULL, false),
  ('2.2.1', 'Users are warned before a time limit expires and given sufficient opportunity to extend it.', 'manual', NULL, false),
  ('2.2.1', 'Time limit controls are accessible using the keyboard and assistive technologies.', 'manual', NULL, false),
  ('2.2.1', 'Exceptions for real-time events are correctly applied.', 'manual', NULL, false),
  ('2.2.1', 'Time limits longer than 20 hours are correctly identified and excluded from this requirement.', 'manual', NULL, false),
  ('2.2.2', 'Blinking content created using deprecated HTML elements (such as <blink>) is not present.', 'axe-core', 'blink', true),
  ('2.2.2', 'Automatically moving or scrolling content (e.g., carousels, sliders, marquees, animations) provides a user-controlled mechanism to pause, stop, or hide the movement.', 'manual', NULL, false),
  ('2.2.2', 'Automatically updating content (e.g., news tickers, live updates, chat feeds) can be paused, stopped, hidden, or controlled by the user.', 'manual', NULL, false),
  ('2.2.2', 'Controls to pause, stop, or hide moving or updating content are clearly visible and accessible.', 'manual', NULL, false),
  ('2.2.2', 'Pause and control mechanisms are keyboard accessible.', 'manual', NULL, false),
  ('2.2.2', 'Moving or updating content does not resume automatically without user initiation.', 'manual', NULL, false),
  ('2.2.2', 'Marquee elements (<marquee>) that cause automatic scrolling or movement are not present on the page.', 'axe-core', 'marquee', true),
  ('2.2.2', 'Automatically moving content implemented using CSS or JavaScript (such as carousels, sliders, or animations) can be paused, stopped, or hidden by the user.', 'manual', NULL, false),
  ('2.2.2', 'Automatically updating content (such as tickers, live feeds, or chat messages) provides user control to pause, stop, hide, or adjust update timing.', 'manual', NULL, false),
  ('2.2.2', 'Controls to pause, stop, or hide moving or updating content are clearly visible and understandable.', 'manual', NULL, false),
  ('2.2.2', 'Pause and control mechanisms are fully keyboard accessible.', 'manual', NULL, false),
  ('2.2.2', 'Automatically moving or updating content does not restart without explicit user action.', 'manual', NULL, false),
  ('2.2.4', 'Pages do not use meta refresh to automatically reload or redirect content without providing a mechanism for users to postpone or control the interruption.', 'axe-core', 'meta-refresh-no-exceptions', true),
  ('2.2.4', 'Alerts, notifications, and updates initiated by scripts can be postponed, suppressed, or controlled by the user.', 'manual', NULL, false),
  ('2.2.4', 'Users are provided with clear controls to pause, stop, or delay interruptions.', 'manual', NULL, false),
  ('2.2.4', 'Interruptions do not occur unexpectedly or without user consent.', 'manual', NULL, false),
  ('2.2.4', 'Time-based updates provide sufficient warning and user control.', 'manual', NULL, false),
  ('2.2.4', 'User preferences for reducing interruptions are respected.', 'manual', NULL, false),
  ('2.2.5', 'If an authentication session expires, the user can re-authenticate and continue the activity without losing any data', 'manual', NULL, false),
  ('2.2.5', 'from the current page.', 'manual', NULL, false),
  ('2.3.1', 'No page content flashes more than 3 times per second unless that flashing content is sufficiently small and the flashes are of low contrast and do not contain too much red. (See general flash and red flash thresholds)', 'manual', NULL, false),
  ('2.3.2', 'No page content flashes more than 3 times per second.', 'manual', NULL, false),
  ('2.3.3', 'Users can disable non-essential animation and movement that is triggered by user interaction', 'manual', NULL, false),
  ('2.4.1', 'Page content uses landmark regions (ARIA or HTML5 landmarks) to identify major sections of the page.', 'axe-core', 'region', true),
  ('2.4.1', 'A visible and operable “skip to main content” (or equivalent) link is provided.', 'manual', NULL, false),
  ('2.4.1', 'The skip link is keyboard accessible and receives focus when tabbing.', 'manual', NULL, false),
  ('2.4.1', 'Activating the skip link moves focus past repeated navigation to the main content.', 'manual', NULL, false),
  ('2.4.1', 'The skip mechanism works consistently across pages with repeated content.', 'manual', NULL, false),
  ('2.4.1', 'Headings and landmark regions are used logically to support content bypass for assistive technology users.', 'manual', NULL, false),
  ('2.4.1', 'A mechanism exists to bypass blocks of repeated content, such as a skip link, landmark region, or equivalent bypass method.', 'axe-core', 'bypass', true),
  ('2.4.1', 'A visible and operable “skip to main content” (or equivalent) link is provided for keyboard users.', 'manual', NULL, false),
  ('2.4.1', 'The skip link receives keyboard focus in a logical order and is perceivable when focused.', 'manual', NULL, false),
  ('2.4.1', 'Activating the skip link moves keyboard focus past repeated navigation directly to the main content.', 'manual', NULL, false),
  ('2.4.1', 'The bypass mechanism works consistently across pages with repeated navigation or content blocks.', 'manual', NULL, false),
  ('2.4.1', 'Headings and landmark regions are used logically to support efficient content bypass for assistive technology users.', 'manual', NULL, false),
  ('2.4.2', 'The document includes a non-empty and present <title> element in the document head.', 'axe-core', 'document-title', true),
  ('2.4.2', 'The page title is descriptive and accurately reflects the page’s purpose or content.', 'manual', NULL, false),
  ('2.4.2', 'The page title is meaningful and informative for users, including screen reader users.', 'manual', NULL, false),
  ('2.4.2', 'Page titles are unique and distinguishable across different pages of the website or application.', 'manual', NULL, false),
  ('2.4.2', 'The page title updates appropriately when page content or context changes (e.g., single-page applications).', 'manual', NULL, false),
  ('2.4.3', 'The navigation order of links, form controls, etc. is logical and intuitive.', 'manual', NULL, false),
  ('2.4.4', 'Links have accessible names that are not empty and are programmatically determinable.', 'axe-core', 'link-name', true),
  ('2.4.4', 'Link text or accessible name clearly describes the purpose or destination of the link.', 'manual', NULL, false),
  ('2.4.4', 'Link purpose can be understood from the link text alone or in combination with surrounding context (such as headings, list items, or table headers).', 'manual', NULL, false),
  ('2.4.4', 'Links with identical text that point to different destinations are visually and programmatically distinguishable.', 'manual', NULL, false),
  ('2.4.4', 'Image links and image buttons convey their purpose through meaningful alternative text.', 'manual', NULL, false),
  ('2.4.4', 'Link purpose remains clear when links are read out of context (e.g., via a screen reader links list).', 'manual', NULL, false),
  ('2.4.4', 'Image map area (<area>) elements have non-empty alternative text that provides an accessible name.', 'axe-core', 'area-alt', true),
  ('2.4.4', 'The alternative text for image map hotspots clearly describes the purpose or destination of each link.', 'manual', NULL, false),
  ('2.4.4', 'The purpose of each link can be determined from the link text alone or together with its surrounding context.', 'manual', NULL, false),
  ('2.4.4', 'Links with the same text that point to different destinations are readily distinguishable.', 'manual', NULL, false),
  ('2.4.4', 'Image buttons and image links convey their purpose through meaningful alternative text.', 'manual', NULL, false),
  ('2.4.4', 'Link purpose remains clear when links are presented out of context (e.g., screen reader links list).', 'manual', NULL, false),
  ('2.4.5', 'Multiple ways are available to find other web pages on the site - at least two of: a list of related pages, table of', 'manual', NULL, false),
  ('2.4.5', 'contents, site map, site search, or list of all available web pages.', 'manual', NULL, false),
  ('2.4.6', 'Heading levels follow a logical and sequential order without skipping levels (e.g., h1 → h2 → h3).', 'axe-core', 'heading-order', true),
  ('2.4.6', 'Headings accurately and informatively describe the content or section they introduce.', 'manual', NULL, false),
  ('2.4.6', 'Form labels and labels for interactive controls clearly describe their purpose.', 'manual', NULL, false),
  ('2.4.6', 'Duplicate headings or labels are avoided unless context or structure makes their purpose clear.', 'manual', NULL, false),
  ('2.4.6', 'Headings provide a clear outline and hierarchy that helps users understand page organization.', 'manual', NULL, false),
  ('2.4.6', 'Headings and labels remain meaningful when accessed out of visual context (e.g., via assistive technology lists).', 'manual', NULL, false),
  ('2.4.7', 'There is a visible indicator for page elements when they receive keyboard focus.', 'manual', NULL, false),
  ('2.4.8', 'If a web page is part of a sequence of pages or within a complex site structure, an indication of the current page', 'manual', NULL, false),
  ('2.4.8', 'location is provided, for example, through breadcrumbs or specifying the current step in a sequence (e.g., "Step 2 of 5- Shipping Address").', 'manual', NULL, false),
  ('2.4.9', 'Links that have identical accessible names point to the same destination, ensuring that identical link text does not lead to different locations.', 'axe-core', 'identical-links-same-purpose', true),
  ('2.4.9', 'Each link’s text alone clearly and accurately describes its purpose without relying on surrounding context.', 'manual', NULL, false),
  ('2.4.9', 'Image links, image buttons, and image map hotspots have text alternatives that clearly convey their purpose.', 'manual', NULL, false),
  ('2.4.9', 'Link text is meaningful, descriptive, and not vague (for example, avoiding “click here” or “more”).', 'manual', NULL, false),
  ('2.4.9', 'Links that appear visually similar but have different purposes are clearly differentiated by their text.', 'manual', NULL, false),
  ('2.4.9', 'The purpose of links remains clear when presented out of visual context (for example, in a list of links).', 'manual', NULL, false),
  ('2.4.10', 'Headings follow a logical and hierarchical order without skipping heading levels.', 'axe-core', '- heading-order (partial)', true),
  ('2.4.10', 'All meaningful sections of content are identified using headings where appropriate.', 'manual', NULL, false),
  ('2.4.10', 'Headings accurately describe the content or purpose of their respective sections.', 'manual', NULL, false),
  ('2.4.10', 'Headings are used consistently to organize content and improve navigability.', 'manual', NULL, false),
  ('2.4.10', 'Headings are not used solely for visual styling purposes.', 'manual', NULL, false),
  ('2.4.10', 'Section headings remain meaningful when accessed via assistive technology (e.g., headings list).', 'manual', NULL, false),
  ('2.5.1', 'If multipoint or path-based gestures (such as pinching, swiping, or dragging across the screen) are not essential to the functionality, then the functionality can also be performed with a single point activation (such as activating a button).', 'manual', NULL, false),
  ('2.5.2', 'To help avoid inadvertent activation of controls, avoid non-essential down-event (e.g., onmousedown) activation when clicking, tapping, or long pressing the screen. Use onclick, onmouseup, or similar instead. If onmouseup (or similar) is used, you must provide a mechanism to abort or undo the action performed.', 'manual', NULL, false),
  ('2.5.3', 'The accessible name of an interactive component contains the visible text presented to users.', 'axe-core', 'label-content-name-mismatch', true),
  ('2.5.3', 'The accessible name includes the visible text in the same order and without altering its meaning.', 'manual', NULL, false),
  ('2.5.3', 'Accessible names derived from aria-label or aria-labelledby accurately reflect the visible label text.', 'manual', NULL, false),
  ('2.5.3', 'Image buttons and icons with visible text equivalents include that text in the accessible name.', 'manual', NULL, false),
  ('2.5.3', 'Dynamic changes to visible labels are reflected in the accessible name.', 'manual', NULL, false),
  ('2.5.3', 'Abbreviations or symbols used visually are appropriately represented in the accessible name.', 'manual', NULL, false),
  ('2.5.4', 'Functionality that is triggered by moving the device (such as shaking or panning a mobile device) or by user movement (such as waving to a camera) can be disabled and equivalent functionality is provided via standard controls like buttons.', 'manual', NULL, false),
  ('2.5.5', 'Clickable targets are at least 44 by 44 pixels in size unless an alternative target of that size is provided, the target is', 'manual', NULL, false),
  ('2.5.5', 'inline (such as a link within a sentence), the target is not author-modified (such as a default checkbox), or the small', 'manual', NULL, false),
  ('2.5.5', 'target size is essential to the functionality.', 'manual', NULL, false),
  ('2.5.6', 'Content does not require a specific input type, such as touch-only or keyboard-only, but must support alternative', 'manual', NULL, false),
  ('2.5.6', 'inputs (such as using a keyboard on a mobile device).', 'manual', NULL, false),
  ('3.1.1', 'The <html> element includes a valid and non-empty lang attribute.', 'axe-core', 'html-has-lang', true),
  ('3.1.1', 'The lang attribute value correctly identifies the primary language of the page content.', 'manual', NULL, false),
  ('3.1.1', 'The language declared in the lang attribute matches the actual language used throughout the page.', 'manual', NULL, false),
  ('3.1.1', 'The language declaration remains accurate when page content or locale changes dynamically.', 'manual', NULL, false),
  ('3.1.1', 'The lang attribute on the <html> element contains a valid language code according to BCP 47.', 'axe-core', 'html-lang-valid', true),
  ('3.1.1', 'The declared language matches the actual language used throughout the page.', 'manual', NULL, false),
  ('3.1.1', 'The lang attribute and xml:lang attribute, when both are present on the <html> element, do not conflict with each other.', 'axe-core', 'html-xml-lang-mismatch', true),
  ('3.1.1', 'The declared language correctly identifies the primary language of the page content.', 'manual', NULL, false),
  ('3.1.1', 'The language specified using lang (and xml:lang, if present) matches the actual language used throughout the page.', 'manual', NULL, false),
  ('3.1.1', 'Language declarations remain accurate when page content or locale changes dynamically.', 'manual', NULL, false),
  ('3.1.2', 'Elements with a lang attribute use a valid language code according to BCP 47.', 'axe-core', 'valid-lang', true),
  ('3.1.2', 'All passages of content written in a different language from the primary page language are correctly identified using the lang attribute.', 'manual', NULL, false),
  ('3.1.2', 'The language specified in the lang attribute accurately matches the language of the content.', 'manual', NULL, false),
  ('3.1.2', 'Language changes are applied consistently to all relevant text segments (including dynamically generated content).', 'manual', NULL, false),
  ('3.1.2', 'Nested language changes are correctly marked when multiple languages appear within the same content block.', 'manual', NULL, false),
  ('3.1.3', 'Words that may be ambiguous, unfamiliar, or used in a very specific way are defined through adjacent text, a', 'manual', NULL, false),
  ('3.1.3', 'definition list, a glossary, or other suitable method.', 'manual', NULL, false),
  ('3.1.4', 'The meaning of an unfamiliar abbreviation is provided by expanding it the first time it is used, using', 'manual', NULL, false),
  ('3.1.4', 'the <abbr> element, or linking to a definition or glossary.', 'manual', NULL, false),
  ('3.1.5', 'A more understandable alternative is provided for content that is more advanced than can be reasonably read by a', 'manual', NULL, false),
  ('3.1.5', 'person with roughly 9 years of primary education.', 'manual', NULL, false),
  ('3.1.6', 'If the pronunciation of a word is vital to understanding that word, its pronunciation is provided immediately following the word or via a link or glossary', 'manual', NULL, false),
  ('3.2.1', 'When a page element receives focus, it does not result in a substantial change to the page, the spawning of a pop-up window, an additional change of keyboard focus, or any other change that could confuse or disorient the user.', 'manual', NULL, false),
  ('3.2.2', 'When a user inputs information or interacts with a control, it does not result in a substantial change to the page, the spawning of a pop-up window, an additional change of keyboard focus, or any other change that could confuse or disorient the user unless the user is informed of the change ahead of time.', 'manual', NULL, false),
  ('3.2.3', 'Navigation links that are repeated on web pages do not change order when navigating through the site', 'manual', NULL, false),
  ('3.2.4', 'Elements that have the same functionality across multiple web pages are consistently identified. For example, a search box at the top of the site should always be labeled the same way.', 'manual', NULL, false),
  ('3.2.5', 'Substantial changes to the page, the spawning of pop-up windows, uncontrolled changes of keyboard focus, or any', 'manual', NULL, false),
  ('3.2.5', 'other change that could confuse or disorient the user must be initiated by the user. Alternatively, the user is provided', 'manual', NULL, false),
  ('3.2.5', 'an option to disable such changes.', 'manual', NULL, false),
  ('3.3.1', 'Required inputs or inputs that require a specific format, value, or length provide this information within the', 'manual', NULL, false),
  ('3.3.1', 'element''s label.', 'manual', NULL, false),
  ('3.3.1', 'Form validation errors are efficient, intuitive, and accessible. The error is clearly identified, quick access to the', 'manual', NULL, false),
  ('3.3.1', 'problematic element is provided, and the user can easily fix the error and resubmit the form.', 'manual', NULL, false),
  ('3.3.2', 'Form controls do not have multiple visible or programmatic labels that would cause confusion for assistive technology users.', 'axe-core', 'form-field-multiple-labels', true),
  ('3.3.2', 'Labels or instructions clearly describe the expected input in a way users can easily understand.', 'manual', NULL, false),
  ('3.3.2', 'Instructions provide sufficient guidance when specific formats, values, or input expectations are required.', 'manual', NULL, false),
  ('3.3.2', 'Labels or instructions are meaningful, descriptive, and not ambiguous.', 'manual', NULL, false),
  ('3.3.2', 'Instructions are available to users before input is required.', 'manual', NULL, false),
  ('3.3.2', 'Visual placement and wording of labels or instructions make the association with the input clear.', 'manual', NULL, false),
  ('3.3.3', 'If an input error is detected (via client-side or server-side validation), suggestions are provided for fixing the input in', 'manual', NULL, false),
  ('3.3.3', 'a timely and accessible manner.', 'manual', NULL, false),
  ('3.3.4', 'Submissions, changes, and deletions of legal, financial, or test data can be reversed, verified, or confirmed.', 'manual', NULL, false),
  ('3.3.5', 'Instructions and cues are provided in context to help in form completion and submission', 'manual', NULL, false),
  ('3.3.6', 'If the user can submit information, the submission is reversible, verified, or confirmed', 'manual', NULL, false),
  ('4.1.1', 'Active elements (such as focusable or interactive elements) do not have duplicate id attribute values that could interfere with DOM parsing and assistive technology interaction.', 'axe-core', NULL, true),
  ('4.1.1', 'Non-active elements are reviewed to ensure they also do not contain duplicate id values.', 'manual', NULL, false),
  ('4.1.1', 'Dynamically generated or updated content is checked to confirm duplicate IDs are not introduced after page load.', 'manual', NULL, false),
  ('4.1.1', 'Overall HTML parsing and markup validity are reviewed to identify other errors that could impact assistive technologies.', 'manual', NULL, false),
  ('4.1.1', 'Elements do not have duplicate id attribute values, ensuring unique identifiers in the DOM and preventing parsing and assistive technology conflicts.', 'axe-core', NULL, true),
  ('4.1.1', 'HTML markup is reviewed to ensure no other parsing errors exist that could affect assistive technology behavior.', 'manual', NULL, false),
  ('4.1.1', 'Custom components and dynamically generated content are verified to ensure unique IDs are maintained at runtime.', 'manual', NULL, false),
  ('4.1.2', 'Elements with ARIA role attributes use valid, defined ARIA roles that are supported according to the ARIA specification.', 'axe-core', 'aria-roles', true),
  ('4.1.2', 'Native HTML elements are used wherever possible instead of ARIA roles.', 'manual', NULL, false),
  ('4.1.2', 'ARIA roles are used only when HTML semantics are insufficient.', 'manual', NULL, false),
  ('4.1.2', 'The assigned role correctly matches the element’s purpose and behavior.', 'manual', NULL, false),
  ('4.1.2', 'Required ARIA states and properties for the assigned role are provided.', 'manual', NULL, false),
  ('4.1.2', 'Accessible names, roles, and values are properly exposed to assistive technologies during interaction.', 'manual', NULL, false),
  ('4.1.2', 'Custom widgets correctly manage state changes and user interaction feedback.', 'manual', NULL, false),
  ('4.1.2', 'Area elements within image maps have a non-empty alt attribute, ensuring an accessible name is programmatically available for each interactive region.', 'axe-core', 'area-alt', true),
  ('4.1.2', 'The alt text for each area accurately reflects the purpose, role, and function of the interactive region.', 'manual', NULL, false),
  ('4.1.2', 'Accessible names exposed through alt text are meaningful and correctly announced by assistive technologies.', 'manual', NULL, false),
  ('4.1.2', 'Image map areas use appropriate native HTML semantics rather than ARIA where possible.', 'manual', NULL, false),
  ('4.1.2', 'The role and value of interactive regions are correctly conveyed during user interaction.', 'manual', NULL, false),
  ('4.1.2', 'Dynamic updates to image maps preserve correct accessible names and roles.', 'manual', NULL, false),
  ('4.1.2', 'ARIA attributes used on elements are permitted for the element’s assigned role, ensuring only allowed ARIA states and properties are applied.', 'axe-core', 'aria-allowed-attr', true),
  ('4.1.2', 'Native HTML elements are used wherever possible instead of ARIA attributes.', 'manual', NULL, false),
  ('4.1.2', 'ARIA attributes are used only when HTML semantics are insufficient.', 'manual', NULL, false),
  ('4.1.2', 'The combination of role, state, and property correctly represents the element’s purpose.', 'manual', NULL, false),
  ('4.1.2', 'Required ARIA states and properties for custom widgets are fully implemented.', 'manual', NULL, false),
  ('4.1.2', 'Accessible names, roles, and values are correctly exposed and updated during user interaction.', 'manual', NULL, false),
  ('4.1.2', 'Custom components behave consistently across assistive technologies.', 'manual', NULL, false),
  ('4.1.2', 'Elements that use ARIA braille-related properties provide a valid braille equivalent so that information is correctly exposed to braille assistive technologies.', 'axe-core', 'aria-braille-equivalent', true),
  ('4.1.2', 'The braille equivalent accurately conveys the same meaning and purpose as the visual or text content.', 'manual', NULL, false),
  ('4.1.2', 'Braille output is meaningful, understandable, and appropriate for the context of use.', 'manual', NULL, false),
  ('4.1.2', 'Native HTML semantics are used wherever possible instead of relying on ARIA braille properties.', 'manual', NULL, false),
  ('4.1.2', 'ARIA braille properties are used only when necessary and according to specification.', 'manual', NULL, false),
  ('4.1.2', 'Updates to content dynamically refresh the corresponding braille output.', 'manual', NULL, false),
  ('4.1.2', 'The exposed name, role, and value remain consistent across different assistive technologies.', 'manual', NULL, false),
  ('4.1.2', 'Elements with ARIA command roles (such as button, menuitem, or link) have an accessible name so assistive technologies can announce the command to users.', 'axe-core', 'aria-command-name', true),
  ('4.1.2', 'The accessible name clearly and accurately describes the purpose or action of the command.', 'manual', NULL, false),
  ('4.1.2', 'The visible label and accessible name are consistent and do not conflict.', 'manual', NULL, false),
  ('4.1.2', 'Native HTML controls are used instead of ARIA command roles wherever possible.', 'manual', NULL, false),
  ('4.1.2', 'The role assigned to the element correctly matches its behavior and function.', 'manual', NULL, false),
  ('4.1.2', 'State and value changes for the command are properly communicated to assistive technologies.', 'manual', NULL, false),
  ('4.1.2', 'Custom command widgets are fully operable and understandable across assistive technologies.', 'manual', NULL, false),
  ('4.1.2', 'Elements with ARIA roles correctly use conditional ARIA attributes only when the assigned role requires or allows them, ensuring valid role–attribute relationships.', 'axe-core', 'aria-conditional-attr', true),
  ('4.1.2', 'Native HTML elements are used instead of ARIA wherever possible.', 'manual', NULL, false),
  ('4.1.2', 'ARIA roles are applied only when HTML semantics are insufficient.', 'manual', NULL, false),
  ('4.1.2', 'Conditional ARIA attributes accurately reflect the current state or behavior of the element.', 'manual', NULL, false),
  ('4.1.2', 'Required ARIA states and properties for the role are fully implemented.', 'manual', NULL, false),
  ('4.1.2', 'State changes are dynamically updated and announced to assistive technologies.', 'manual', NULL, false),
  ('4.1.2', 'The exposed name, role, and value remain accurate throughout user interaction.', 'manual', NULL, false),
  ('4.1.2', 'Elements do not use deprecated ARIA roles, ensuring only current and supported roles are exposed to assistive technologies.', 'axe-core', 'aria-deprecated-role', true),
  ('4.1.2', 'Native HTML elements are used instead of ARIA roles wherever possible.', 'manual', NULL, false),
  ('4.1.2', 'ARIA roles accurately match the element’s purpose and behavior.', 'manual', NULL, false),
  ('4.1.2', 'Required ARIA states and properties for the assigned role are correctly implemented.', 'manual', NULL, false),
  ('4.1.2', 'Accessible names, roles, and values are properly exposed and updated during interaction.', 'manual', NULL, false),
  ('4.1.2', 'Custom widgets behave consistently across different assistive technologies.', 'manual', NULL, false),
  ('4.1.2', 'The document body element is not hidden from assistive technologies using aria-hidden, ensuring that page content remains available to users of screen readers.', 'axe-core', 'aria-hidden-body', true),
  ('4.1.2', 'Content intended to be hidden from assistive technologies is appropriately managed without affecting the overall accessibility of the page.', 'manual', NULL, false),
  ('4.1.2', 'aria-hidden is used only on elements that should be excluded from the accessibility tree.', 'manual', NULL, false),
  ('4.1.2', 'Interactive and focusable content is never hidden from assistive technologies while remaining visible to sighted users.', 'manual', NULL, false),
  ('4.1.2', 'Dynamic changes to visibility correctly update accessibility exposure.', 'manual', NULL, false),
  ('4.1.2', 'The accessible name, role, and value of elements remain accurate throughout user interaction.', 'manual', NULL, false),
  ('4.1.2', 'Elements that are hidden from assistive technologies using aria-hidden do not receive keyboard focus, preventing inaccessible focusable content.', 'axe-core', 'aria-hidden-focus', true),
  ('4.1.2', 'Focus management is logically handled when content is shown or hidden.', 'manual', NULL, false),
  ('4.1.2', 'aria-hidden is used only on content that should be completely inaccessible to assistive technologies.', 'manual', NULL, false),
  ('4.1.2', 'Interactive elements are never hidden from assistive technologies while remaining visible or focusable.', 'manual', NULL, false),
  ('4.1.2', 'Dynamic visibility changes correctly update focus order and accessibility exposure.', 'manual', NULL, false),
  ('4.1.2', 'The accessible name, role, and value of interactive elements remain accurate during user interaction.', 'manual', NULL, false),
  ('4.1.2', 'Input elements have an accessible name provided via label, aria-label, or aria-labelledby so assistive technologies can announce the input’s purpose.', 'axe-core', 'aria-input-field-name', true),
  ('4.1.2', 'The accessible name clearly and accurately describes the expected input.', 'manual', NULL, false),
  ('4.1.2', 'Visible labels and accessible names are consistent and do not conflict.', 'manual', NULL, false),
  ('4.1.2', 'Instructions or hints needed to understand the input are clearly provided to users.', 'manual', NULL, false),
  ('4.1.2', 'Native HTML labeling mechanisms are used instead of ARIA where possible.', 'manual', NULL, false),
  ('4.1.2', 'Changes to input state or context do not break the accessible name exposure.', 'manual', NULL, false),
  ('4.1.2', 'Elements do not use ARIA attributes that are explicitly prohibited for their assigned role, ensuring valid role–attribute usage.', 'axe-core', 'aria-prohibited-attr', true),
  ('4.1.2', 'The combination of role, state, and property accurately represents the element’s purpose and behavior.', 'manual', NULL, false),
  ('4.1.2', 'Required ARIA states and properties for custom widgets are correctly implemented.', 'manual', NULL, false),
  ('4.1.2', 'Accessible names, roles, and values are properly exposed and updated during user interaction.', 'manual', NULL, false),
  ('4.1.2', 'Custom components behave consistently across different assistive technologies.', 'manual', NULL, false),
  ('4.1.2', 'Elements that use the aria-required attribute apply it only to supported form controls and with valid values, ensuring the required state is correctly exposed to assistive technologies.', 'axe-core', 'aria-required-attr', true),
  ('4.1.2', 'Required fields are clearly communicated to users through visible labels or instructions, not only programmatically.', 'manual', NULL, false),
  ('4.1.2', 'Native HTML required attributes are used instead of ARIA where possible.', 'manual', NULL, false),
  ('4.1.2', 'The required state accurately reflects the actual validation behavior of the form control.', 'manual', NULL, false),
  ('4.1.2', 'Accessible names, roles, and values remain correct during user interaction.', 'manual', NULL, false),
  ('4.1.2', 'Error handling and feedback related to required fields are clearly communicated to users.', 'manual', NULL, false),
  ('4.1.2', 'Toggle form controls (such as switches, checkboxes, or toggle buttons) have an accessible name provided via label, aria-label, or aria-labelledby so assistive technologies can announce the control and its state.', 'axe-core', 'aria-toggle-field-name', true),
  ('4.1.2', 'The accessible name clearly describes the purpose and effect of the toggle control.', 'manual', NULL, false),
  ('4.1.2', 'The current state of the toggle (on/off, checked/unchecked) is clearly conveyed to users.', 'manual', NULL, false),
  ('4.1.2', 'Native HTML toggle controls are used instead of ARIA where possible.', 'manual', NULL, false),
  ('4.1.2', 'State changes are correctly updated and announced to assistive technologies during interaction.', 'manual', NULL, false),
  ('4.1.2', 'Custom toggle components behave consistently across different assistive technologies.', 'manual', NULL, false),
  ('4.1.2', 'Elements with the ARIA tooltip role have an accessible name so assistive technologies can identify and announce the tooltip content.', 'axe-core', 'aria-tooltip-name', true),
  ('4.1.2', 'Tooltip text clearly and accurately describes the information being provided.', 'manual', NULL, false),
  ('4.1.2', 'Tooltips are triggered in a way that is accessible to keyboard and assistive technology users.', 'manual', NULL, false),
  ('4.1.2', 'Tooltip content remains available long enough for users to read and understand it.', 'manual', NULL, false),
  ('4.1.2', 'Native HTML mechanisms are used instead of ARIA tooltips where possible.', 'manual', NULL, false),
  ('4.1.2', 'The relationship between the tooltip and its triggering element is clear to users.', 'manual', NULL, false),
  ('4.1.2', 'Dynamic tooltip content updates are correctly announced to assistive technologies.', 'manual', NULL, false),
  ('4.1.2', 'ARIA attributes used on elements have valid values according to the ARIA specification, ensuring states and properties are correctly exposed to assistive technologies.', 'axe-core', 'aria-valid-attr-value', true),
  ('4.1.2', 'ARIA attributes accurately reflect the current state, role, and value of the element.', 'manual', NULL, false),
  ('4.1.2', 'Required ARIA states and properties for the assigned role are fully implemented.', 'manual', NULL, false),
  ('4.1.2', 'Changes to ARIA state and value are dynamically updated and announced to assistive technologies.', 'manual', NULL, false),
  ('4.1.2', 'Accessible names, roles, and values remain accurate and meaningful throughout user interaction.', 'manual', NULL, false),
  ('4.1.2', 'Only valid ARIA attributes are used on elements according to the ARIA specification, preventing unsupported or invalid attributes from being exposed to assistive technologies.', 'axe-core', 'aria-valid-attr', true),
  ('4.1.2', 'ARIA attributes are applied only when HTML semantics are insufficient.', 'manual', NULL, false),
  ('4.1.2', 'The combination of role, state, and property accurately represents the element’s purpose.', 'manual', NULL, false),
  ('4.1.2', 'Accessible names, roles, and values are correctly exposed and updated during interaction.', 'manual', NULL, false),
  ('4.1.2', 'Button elements have an accessible name provided via visible text, aria-label, aria-labelledby, or equivalent mechanisms so assistive technologies can announce the button’s purpose.', 'axe-core', 'button-name', true),
  ('4.1.2', 'The button’s accessible name clearly and accurately describes the action it performs.', 'manual', NULL, false),
  ('4.1.2', 'Native HTML button elements are used instead of ARIA roles wherever possible.', 'manual', NULL, false),
  ('4.1.2', 'State changes (such as pressed or expanded) are correctly conveyed to users.', 'manual', NULL, false),
  ('4.1.2', 'Buttons behave consistently across keyboard, screen reader, and other assistive technologies.', 'manual', NULL, false),
  ('4.1.2', 'Dynamic updates related to button actions correctly update accessible name, role, or value when applicable.', 'manual', NULL, false),
  ('4.1.2', 'ARIA attributes that reference IDs (such as aria-labelledby, aria-describedby, aria-controls) do not reference duplicate id values, ensuring assistive technologies can correctly resolve relationships.', 'axe-core', 'duplicate-id-aria', true),
  ('4.1.2', 'All referenced IDs accurately point to the correct elements that provide names, descriptions, or relationships.', 'manual', NULL, false),
  ('4.1.2', 'Referenced elements contain meaningful and appropriate content for accessibility.', 'manual', NULL, false),
  ('4.1.2', 'Native HTML relationships are used instead of ARIA references wherever possible.', 'manual', NULL, false),
  ('4.1.2', 'Dynamically generated content does not introduce duplicate IDs after page load.', 'manual', NULL, false),
  ('4.1.2', 'The accessible name, role, and value remain accurate during interaction with referenced elements.', 'manual', NULL, false),
  ('4.1.2', 'Frames and iframes have unique title attribute values so assistive technologies can distinguish between different frames on the page.', 'axe-core', 'frame-title-unique', true),
  ('4.1.2', 'Frame and iframe titles clearly and accurately describe the content or purpose of each frame.', 'manual', NULL, false),
  ('4.1.2', 'Titles are meaningful, descriptive, and not generic (for example, not repeated values like “frame” or “iframe”).', 'manual', NULL, false),
  ('4.1.2', 'Frames are used only when necessary and are structured appropriately.', 'manual', NULL, false),
  ('4.1.2', 'The relationship between frames and surrounding content is clear to users.', 'manual', NULL, false),
  ('4.1.2', 'Dynamic updates to frame content preserve correct and meaningful titles.', 'manual', NULL, false),
  ('4.1.2', 'Frame and iframe elements have a title attribute so assistive technologies can identify and announce the frame.', 'axe-core', 'frame-title', true),
  ('4.1.2', 'Titles are meaningful and descriptive, not generic or ambiguous.', 'manual', NULL, false),
  ('4.1.2', 'Frames are used only when necessary and structured appropriately within the page.', 'manual', NULL, false),
  ('4.1.2', 'The relationship between frame content and surrounding page content is clear to users.', 'manual', NULL, false),
  ('4.1.2', 'Input elements of type button, submit, or reset have an accessible name provided via the value attribute, aria-label, aria-labelledby, or equivalent mechanisms so assistive technologies can announce the button’s purpose.', 'axe-core', 'input-button-name', true),
  ('4.1.2', 'The input button’s accessible name clearly and accurately describes the action it performs.', 'manual', NULL, false),
  ('4.1.2', 'Native HTML input button types are used appropriately instead of ARIA where possible.', 'manual', NULL, false),
  ('4.1.2', 'State or context changes triggered by the button are clearly communicated to users.', 'manual', NULL, false),
  ('4.1.2', 'Input buttons behave consistently across keyboard, screen reader, and other assistive technologies.', 'manual', NULL, false),
  ('4.1.2', 'Input elements of type="image" have a non-empty alt attribute so an accessible name is programmatically available to assistive technologies.', 'axe-core', 'input-image-alt', true),
  ('4.1.2', 'The alt text accurately describes the purpose or action of the image input control.', 'manual', NULL, false),
  ('4.1.2', 'The accessible name provided by alt text is meaningful and equivalent to the control’s function.', 'manual', NULL, false),
  ('4.1.2', 'Native HTML input image semantics are used appropriately without unnecessary ARIA.', 'manual', NULL, false),
  ('4.1.2', 'The role, name, and value exposed by the image input remain accurate during interaction.', 'manual', NULL, false),
  ('4.1.2', 'Dynamic updates or state changes related to the image input are correctly conveyed to assistive technologies.', 'manual', NULL, false),
  ('4.1.2', 'Form controls have an associated programmatic label using label elements, aria-label, or aria-labelledby so assistive technologies can determine the control’s accessible name.', 'axe-core', 'label', true),
  ('4.1.2', 'Labels clearly and accurately describe the purpose of each form control.', 'manual', NULL, false),
  ('4.1.2', 'Dynamic changes to labels or form context preserve correct accessible name exposure.', 'manual', NULL, false),
  ('4.1.2', 'Interactive elements are not nested within other interactive elements, preventing invalid role, focus, and interaction conflicts for assistive technologies.', 'axe-core', 'nested-interactive', true),
  ('4.1.2', 'Interactive controls have a single, clear role and purpose.', 'manual', NULL, false),
  ('4.1.2', 'Focus order and keyboard interaction behave predictably for interactive elements.', 'manual', NULL, false),
  ('4.1.2', 'Native HTML controls are used instead of custom nested interactive structures where possible.', 'manual', NULL, false),
  ('4.1.2', 'The accessible name, role, and value of interactive elements remain accurate during interaction.', 'manual', NULL, false),
  ('4.1.2', 'Custom interaction patterns are consistently exposed across assistive technologies.', 'manual', NULL, false),
  ('4.1.2', 'Select (dropdown) elements have an accessible name provided via label, aria-label, or aria-labelledby so assistive technologies can announce the purpose of the control.', 'axe-core', 'select-name', true),
  ('4.1.2', 'The accessible name clearly and accurately describes the purpose of the select control.', 'manual', NULL, false),
  ('4.1.2', 'Instructions or context needed to understand available options are clearly provided.', 'manual', NULL, false),
  ('4.1.2', 'Native HTML select elements are used instead of ARIA where possible.', 'manual', NULL, false),
  ('4.1.2', 'Changes to available options or selected values are correctly conveyed to assistive technologies.', 'manual', NULL, false),
  ('4.1.2', 'Summary elements (used with details) have an accessible name so assistive technologies can announce the purpose of the expandable control.', 'axe-core', 'summary-name', true),
  ('4.1.2', 'The summary text clearly and accurately describes the content that will be revealed.', 'manual', NULL, false),
  ('4.1.2', 'The visible summary text and accessible name are consistent and do not conflict.', 'manual', NULL, false),
  ('4.1.2', 'The expanded and collapsed states are clearly conveyed to users.', 'manual', NULL, false),
  ('4.1.2', 'Native HTML details/summary elements are used appropriately without unnecessary ARIA.', 'manual', NULL, false),
  ('4.1.2', 'State changes (expanded/collapsed) are correctly announced to assistive technologies.', 'manual', NULL, false),
  ('4.1.2', 'Link elements have an accessible name provided via link text, aria-label, aria-labelledby, or equivalent mechanisms so assistive technologies can announce the link’s purpose.', 'axe-core', 'link-name', true),
  ('4.1.2', 'The link’s accessible name clearly and accurately describes the destination or action.', 'manual', NULL, false),
  ('4.1.2', 'The visible link text and accessible name are consistent and do not conflict.', 'manual', NULL, false),
  ('4.1.2', 'Native HTML link elements are used instead of ARIA roles wherever possible.', 'manual', NULL, false),
  ('4.1.2', 'Links are distinguishable and understandable when presented out of context.', 'manual', NULL, false),
  ('4.1.2', 'Dynamic updates to link text or purpose correctly update the accessible name.', 'manual', NULL, false),
  ('4.1.2', 'Elements that use aria-roledescription provide a valid, non-empty value so assistive technologies can announce a human-readable description of the element’s role.', 'axe-core', NULL, true),
  ('4.1.2', 'aria-roledescription is used only to enhance understanding and does not replace correct native roles.', 'manual', NULL, false),
  ('4.1.2', 'The role description accurately reflects the element’s actual purpose and behavior.', 'manual', NULL, false),
  ('4.1.2', 'Native HTML semantics are used instead of ARIA wherever possible.', 'manual', NULL, false),
  ('4.1.2', 'The underlying ARIA role remains correct and appropriate for the element.', 'manual', NULL, false),
  ('4.1.2', 'Accessible names, roles, and values remain accurate during user interaction.', 'manual', NULL, false),
  ('4.1.3', 'If an important status message is presented and focus is not set to that message, the message must be announced to', 'manual', NULL, false),
  ('4.1.3', 'screen reader users, typically via an ARIA alert or live region.', 'manual', NULL, false);

-- Sample data removed to prevent stale findings on fresh install.
-- Use the application to generate real data.

