-- Safe seed - Only updates reference conditions without deleting audit data
-- This preserves your pages, audits, findings, and scan results

-- Only truncate the reference table
TRUNCATE TABLE reference_sc_conditions RESTART IDENTITY CASCADE;

-- Repopulate with the latest conditions
INSERT INTO reference_sc_conditions (sc_id, condition_text, condition_type, axe_rule_id) VALUES
   ('1.1.1', 'Images have alternative text where required (non-decorative images).', 'axe-core', 'image-alt'),
  ('1.1.1', 'Decorative images are marked with empty alternative text (alt="") or implemented as CSS backgrounds.', 'axe-core', 'image-alt'),
  ('1.1.1', 'Linked images have descriptive and meaningful alternative text.', 'manual', NULL),
  ('1.1.1', 'Equivalent text alternatives for complex images are provided in context or via a separate linked page.', 'manual', NULL),
  ('1.1.1', 'Form buttons have descriptive values that convey their purpose.', 'manual', NULL),
  ('1.1.1', 'Inputs have appropriate accessible names.', 'axe-core', 'aria-meter-name, aria-progressbar-name, input-image-alt, role-img-alt, svg-img-alt'),
  ('1.1.1', 'Embedded multimedia is identified using accessible text alternatives.', 'axe-core', 'input-image-alt, object-alt, role-img-alt, svg-img-alt'),
  ('1.1.1', 'Frames and iframes have appropriate and descriptive titles.', 'manual', NULL),
  ('1.2.1', 'Audio-only media elements include a mechanism (such as a track or accessible reference) indicating the presence of a transcript or caption alternative.', 'axe-core', 'audio-caption  (Deprecated)'),
  ('1.2.1', 'A complete and accurate transcript is provided for all non-live audio-only content.', 'manual', NULL),
  ('1.2.1', 'The transcript includes all relevant spoken dialogue and meaningful sounds.', 'manual', NULL),
  ('1.2.1', 'For non-live video-only content, a descriptive transcript or audio description is provided.', 'manual', NULL),
  ('1.2.1', 'Decorative video-only content is correctly identified and does not require a transcript.', 'manual', NULL),
  ('1.2.1', 'Transcripts or audio descriptions are easy to locate and accessible to users.', 'manual', NULL),
  ('1.2.1', 'The transcript or audio description accurately reflects the timing and meaning of the media content.', 'manual', NULL),
  ('1.2.2', 'Prerecorded video elements include a captions track (<track kind="captions">) associated with the video.', 'axe-core', 'video-caption'),
  ('1.2.2', 'Captions are synchronized accurately with the audio.', 'manual', NULL),
  ('1.2.2', 'Captions include all spoken dialogue and relevant non-speech audio (e.g., sound effects).', 'manual', NULL),
  ('1.2.2', 'Captions are complete for the entire duration of the prerecorded video.', 'manual', NULL),
  ('1.2.3', 'A descriptive transcript or audio description is provided for non-live video.', 'manual', NULL),
  ('1.2.3', 'NOTE: Only required if there is relevant visual content that is not presented in the audio.', 'manual', NULL),
  ('1.2.4', 'Synchronized captions are provided for live media that contains audio (audio-only broadcasts, web casts, video conferences, etc.)', 'manual', NULL),
  ('1.2.5', 'Audio descriptions are provided for non-live video.', 'manual', NULL),
  ('1.2.5', 'NOTE: Only required if there is relevant visual content that is not presented in the audio.', 'manual', NULL),
  ('1.2.5', 'While not required at Level AA, for optimal accessibility WebAIM recommends descriptive transcripts in addition to audio descriptions.', 'manual', NULL),
  ('1.2.6', 'A sign language video is provided for media that contains audio', 'manual', NULL),
  ('1.2.7', 'When audio description cannot be added to video due to insufficient pauses in the audio, an alternative version of the video with pauses that allow audio descriptions is provided.', 'manual', NULL),
  ('1.2.8', 'A descriptive transcript is provided for pre-recorded media that has a video track.', 'manual', NULL),
  ('1.2.8', 'For optimal accessibility, WebAIM strongly recommends transcripts for all multimedia.', 'manual', NULL),
  ('1.2.9', 'A descriptive text transcript (e.g., the script of the live audio) is provided for live content that has audio.', 'manual', NULL),
  ('1.3.1', 'ARIA parent roles that require specific child roles contain all required child elements (for example, role="list" contains role="listitem").', 'axe-core', 'aria-required-children, aria-required-parent, list'),
  ('1.3.1', 'Headings, landmarks, lists, and other structural elements are marked up using correct native HTML semantics.', 'axe-core', 'dlitem'),
  ('1.3.1', 'Lists are implemented using appropriate HTML elements (ul, ol, dl) or correct ARIA roles where HTML is insufficient.', 'axe-core', 'list, listitem'),
  ('1.3.1', 'Tables are used only for tabular data and not for layout purposes.', 'manual', NULL),
  ('1.3.1', 'Data table headers are correctly associated with their corresponding data cells.', 'axe-core', 'th-has-data-cells'),
  ('1.3.1', 'Data tables include captions when needed and captions are correctly associated with the tables.', 'manual', NULL),
  ('1.3.1', 'Form inputs have visible and programmatically associated text labels.', 'manual', NULL),
  ('1.3.1', 'Related form controls are grouped using fieldset and legend where appropriate.', 'manual', NULL),
  ('1.3.1', 'ARIA labelling is used correctly only when native HTML semantics are insufficient.', 'manual', NULL),
  ('1.3.2', 'The reading and navigation order (determined by code order) is logical and intuitive', 'manual', NULL),
  ('1.3.3', 'Instructions do not rely upon shape, size, or visual location (e.g., "Click the square icon to continue" or "Instructions are in the right-hand column").', 'manual', NULL),
  ('1.3.3', 'Instructions do not rely upon sound (e.g., "A beeping sound indicates you may continue.")', 'manual', NULL),
  ('1.3.4', 'Orientation of web content is not restricted to only portrait or landscape, unless a specific orientation is necessary.', 'manual', NULL),
  ('1.3.5', 'Form input fields that support autocomplete use valid and appropriate autocomplete attribute values as defined by the HTML specification.', 'axe-core', 'autocomplete-valid'),
  ('1.3.5', 'The selected autocomplete values accurately reflect the intended purpose of each input field (e.g., name, email, address).', 'manual', NULL),
  ('1.3.5', 'Autocomplete attributes are applied to all relevant user data fields where applicable.', 'manual', NULL),
  ('1.3.5', 'Inputs that should not have autocomplete do not include inappropriate autocomplete values.', 'manual', NULL),
  ('1.3.6', 'Regions/landmarks are used to identify page regions.', 'manual', NULL),
  ('1.3.6', 'ARIA is used, where appropriate, to enhance HTML semantics to better identify the purpose of interface components.', 'manual', NULL),
  ('1.4.1', 'Links within blocks of text are visually distinguishable from surrounding text without relying on color alone.', 'axe-core', 'link-in-text-block'),
  ('1.4.1', 'Color is not used as the sole method to convey information, indicate status, prompt action, or distinguish visual elements other than links.', 'manual', NULL),
  ('1.4.1', 'Non-link visual cues (icons, charts, error messages, required fields, instructions) do not rely on color alone.', 'manual', NULL),
  ('1.4.1', 'The contrast ratio between link text and surrounding text is at least 3:1 when color is used to distinguish links.', 'manual', NULL),
  ('1.4.1', 'Links provide an additional visual indicator (such as underline) on hover and keyboard focus.', 'manual', NULL),
  ('1.4.1', 'Visual distinctions conveyed by color are also available programmatically or through text alternatives.', 'manual', NULL),
  ('1.4.2', 'Audio does not automatically play for more than 3 seconds without a user-controlled mechanism to stop or pause it.', 'axe-core', 'no-autoplay-audio'),
  ('1.4.2', 'A visible and operable control is available to pause, stop, or mute the audio.', 'manual', NULL),
  ('1.4.2', 'Audio controls are keyboard accessible.', 'manual', NULL),
  ('1.4.2', 'Users can independently adjust audio volume without affecting system volume.', 'manual', NULL),
  ('1.4.2', 'Audio control mechanisms are clearly labeled and understandable.', 'manual', NULL),
  ('1.4.3', 'Text and images of text meet the minimum contrast ratio of 4.5:1 for normal text.', 'axe-core', 'color-contrast'),
  ('1.4.3', 'Large-scale text meets the minimum contrast ratio of 3:1.', 'axe-core', 'color-contrast'),
  ('1.4.3', 'Text that is part of images is essential and cannot be presented using real text.', 'manual', NULL),
  ('1.4.3', 'Contrast is evaluated correctly for text rendered over gradients, images, patterns, or videos.', 'manual', NULL),
  ('1.4.3', 'Custom fonts, font weights, and font rendering do not reduce effective contrast below minimum thresholds.', 'manual', NULL),
  ('1.4.3', 'Text contrast remains sufficient in all interaction states (hover, focus, active, visited).', 'manual', NULL),
  ('1.4.3', 'Contrast is maintained when user styles, zoom, or high-contrast modes are applied.', 'manual', NULL),
  ('1.4.4', 'The viewport meta tag does not restrict user scaling (e.g., does not disable zoom or set maximum-scale less than 2).', 'axe-core', 'meta-viewport'),
  ('1.4.4', 'Text content remains readable and does not become truncated, overlapped, or clipped when zoomed to 200%.', 'manual', NULL),
  ('1.4.4', 'All functionality remains available and operable when the page is zoomed to 200%.', 'manual', NULL),
  ('1.4.4', 'Horizontal scrolling is not required for reading blocks of text at 200% zoom (except where allowed).', 'manual', NULL),
  ('1.4.4', 'Fixed-position or absolutely positioned content does not obscure text or controls when zoomed.', 'manual', NULL),
  ('1.4.4', 'Interactive elements remain visible, usable, and discoverable at 200% zoom.', 'manual', NULL),
  ('1.4.6', 'Text and images of text meet the enhanced minimum color contrast ratios of 7:1 for normal text and 4.5:1 for large or bold text based on computed foreground and background colors.', 'axe-core', 'color-contrast-enhanced'),
  ('1.4.6', 'Contrast is sufficient in all user states, including hover, focus, active, disabled, and visited states.', 'manual', NULL),
  ('1.4.6', 'Text displayed over images, gradients, patterns, or video maintains the required enhanced contrast ratios.', 'manual', NULL),
  ('1.4.6', 'Contrast remains sufficient when custom user styles, zoom, or high-contrast modes are applied.', 'manual', NULL),
  ('1.4.6', 'Images of text that contain meaningful content meet the enhanced contrast requirements.', 'manual', NULL),
  ('1.4.6', 'Dynamically updated text content maintains enhanced contrast at all times.', 'manual', NULL),
  ('1.4.6', 'Essential visual information conveyed through text is not lost due to insufficient contrast in real-world viewing conditions.', 'manual', NULL),
  ('1.4.7', 'Audio with speech has no or very low background noise so the speech is easily distinguished.', 'manual', NULL),
  ('1.4.8', 'Blocks of text over one sentence in length:', 'manual', NULL),
  ('1.4.8', 'o Are no more than 80 characters wide.', 'manual', NULL),
  ('1.4.8', 'o Are NOT fully justified (aligned to both the left and the right margins).', 'manual', NULL),
  ('1.4.8', 'o Have adequate line spacing (at least 1/2 the height of the text) and paragraph spacing (1.5 times line spacing).', 'manual', NULL),
  ('1.4.8', 'o Have defined or inherited foreground and background colors.', 'manual', NULL),
  ('1.4.8', 'o Do NOT require horizontal scrolling when the text size is doubled.', 'manual', NULL),
  ('1.4.9', 'Images that appear to contain text are programmatically detected and flagged for review.', 'axe-core', 'image-text'),
  ('1.4.9', 'Images containing text are used only for decorative purposes and do not convey essential information.', 'manual', NULL),
  ('1.4.9', 'When images of text convey information, the information cannot be presented using real text alone.', 'manual', NULL),
  ('1.4.9', 'Decorative images of text are appropriately marked so they are ignored by assistive technologies.', 'manual', NULL),
  ('1.4.9', 'Logos, branding, and other allowed exceptions are correctly identified and applied.', 'manual', NULL),
  ('1.4.10', 'No loss of content or functionality occurs, and horizontal scrolling is avoided when content is presented at a width of 320 pixels.', 'manual', NULL),
  ('1.4.10', 'o This requires responsive design for most web sites.', 'manual', NULL),
  ('1.4.10', 'This is best tested by setting the browser window to 1280 pixels wide and then zooming the page content to 400%.', 'manual', NULL),
  ('1.4.10', 'Content that requires horizontal scrolling, such as data tables, complex images (such as maps and charts), toolbars, etc. are exempted.', 'manual', NULL),
  ('1.4.11', 'A contrast ratio of at least 3:1 is present for differentiating graphical objects (such as icons and components of charts or graphs) and author-customized interface components (such as buttons, form controls, and focus indicators/outlines).', 'manual', NULL),
  ('1.4.11', 'At least 3:1 contrast is maintained in the various states (focus, hover, active, etc.) of author-customized interactive components.', 'manual', NULL),
  ('1.4.12', 'Inline styles do not set fixed line-height, letter-spacing, or word-spacing values that would prevent user text spacing adjustments.', 'axe-core', 'avoid-inline-spacing'),
  ('1.4.12', 'Content remains readable and no text is clipped, overlapped, or truncated when paragraph, line, word, and letter spacing are increased to the specified values.', 'manual', NULL),
  ('1.4.12', 'All functionality remains available and operable when text spacing is adjusted.', 'manual', NULL),
  ('1.4.12', 'Fixed heights or containers do not cause loss of content when spacing is increased.', 'manual', NULL),
  ('1.4.12', 'Text spacing adjustments do not require horizontal scrolling to read blocks of text.', 'manual', NULL),
  ('1.4.12', 'Spacing adaptations work consistently across different browsers and assistive technologies.', 'manual', NULL),
  ('1.4.13', 'When additional content is presented on hover or keyboard focus:', 'manual', NULL),
  ('1.4.13', 'o The newly revealed content can be dismissed (generally via the Esc key) without moving the pointer or keyboard focus, unless the content presents an input error or does not obscure or interfere with other page content.', 'manual', NULL),
  ('1.4.13', 'o The pointer can be moved to the new content without the content disappearing.', 'manual', NULL),
  ('1.4.13', 'o The new content must remain visible until the pointer or keyboard focus is moved away from the triggering control, the new content is dismissed, or the new content is no longer relevant.', 'manual', NULL),
  ('2.1.1', 'Scrollable regions that contain keyboard-operable content are focusable using the keyboard.', 'axe-core', 'frame-focusable-content, scrollable-region-focusable'),
  ('2.1.1', 'All interactive elements and functionality on the page can be operated using the keyboard alone.', 'axe-core', 'server-side-image-map'),
  ('2.1.1', 'No functionality requires mouse-only, touch-only, or pointer-specific interactions.', 'manual', NULL),
  ('2.1.1', 'Keyboard focus order allows users to reach and operate all interactive components.', 'manual', NULL),
  ('2.1.1', 'Page-defined shortcut keys and accesskeys do not conflict with browser or assistive technology shortcuts.', 'manual', NULL),
  ('2.1.1', 'Keyboard interactions are consistent and do not trap users within components.', 'manual', NULL),
  ('2.1.2', 'Keyboard focus is never locked or trapped at one particular page element.', 'manual', NULL),
  ('2.1.2', 'The user can navigate to and from all navigable page elements using only a keyboard.', 'manual', NULL),
  ('2.1.3', 'Scrollable regions are keyboard focusable so users can scroll and interact with the content using only the keyboard.', 'axe-core', 'scrollable-region-focusable'),
  ('2.1.3', 'All interactive functionality on the page can be operated using only the keyboard.', 'manual', NULL),
  ('2.1.3', 'Keyboard users can access and operate custom widgets and components.', 'manual', NULL),
  ('2.1.3', 'Keyboard focus order is logical and intuitive throughout the page.', 'manual', NULL),
  ('2.1.3', 'Keyboard traps are not present and users can move focus away from all components.', 'manual', NULL),
  ('2.1.3', 'All keyboard interactions work consistently across browsers and assistive technologies.', 'manual', NULL),
  ('2.1.3', 'Time-based or gesture-based interactions have equivalent keyboard alternatives.', 'manual', NULL),
  ('2.1.4', 'If a keyboard shortcut uses printable character keys, then the user must be able to disable the key command, change the defined key to a non-printable key (Ctrl, Alt, etc.), or only activate the shortcut when an associated interface component or button is focused.', 'manual', NULL),
  ('2.2.1', 'Pages do not use automatic meta refresh mechanisms that refresh or redirect the page without user control.', 'axe-core', 'meta-refresh'),
  ('2.2.1', 'Time limits imposed by scripts, sessions, or applications provide a user-controlled mechanism to turn off, adjust, or extend the time limit.', 'manual', NULL),
  ('2.2.1', 'Users are warned before a time limit expires and given sufficient opportunity to extend it.', 'manual', NULL),
  ('2.2.1', 'Time limit controls are accessible using the keyboard and assistive technologies.', 'manual', NULL),
  ('2.2.1', 'Exceptions for real-time events are correctly applied.', 'manual', NULL),
  ('2.2.1', 'Time limits longer than 20 hours are correctly identified and excluded from this requirement.', 'manual', NULL),
  ('2.2.2', 'Blinking content created using deprecated HTML elements (such as <blink>) is not present.', 'axe-core', 'blink'),
  ('2.2.2', 'Automatically moving or scrolling content (e.g., carousels, sliders, marquees, animations) provides a user-controlled mechanism to pause, stop, or hide the movement.', 'manual', NULL),
  ('2.2.2', 'Automatically updating content (e.g., news tickers, live updates, chat feeds) can be paused, stopped, hidden, or controlled by the user.', 'manual', NULL),
  ('2.2.2', 'Controls to pause, stop, or hide moving or updating content are clearly visible and accessible.', 'manual', NULL),
  ('2.2.2', 'Pause and control mechanisms are keyboard accessible.', 'manual', NULL),
  ('2.2.2', 'Moving or updating content does not resume automatically without user initiation.', 'manual', NULL),
  ('2.2.4', 'Pages do not use meta refresh to automatically reload or redirect content without providing a mechanism for users to postpone or control the interruption.', 'axe-core', 'meta-refresh-no-exceptions'),
  ('2.2.4', 'Alerts, notifications, and updates initiated by scripts can be postponed, suppressed, or controlled by the user.', 'manual', NULL),
  ('2.2.4', 'Users are provided with clear controls to pause, stop, or delay interruptions.', 'manual', NULL),
  ('2.2.4', 'Interruptions do not occur unexpectedly or without user consent.', 'manual', NULL),
  ('2.2.4', 'Time-based updates provide sufficient warning and user control.', 'manual', NULL),
  ('2.2.4', 'User preferences for reducing interruptions are respected.', 'manual', NULL),
  ('2.2.5', 'If an authentication session expires, the user can re-authenticate and continue the activity without losing any data from the current page.', 'manual', NULL),
  ('2.3.1', 'No page content flashes more than 3 times per second unless that flashing content is sufficiently small and the flashes are of low contrast and do not contain too much red. (See general flash and red flash thresholds)', 'manual', NULL),
  ('2.3.2', 'No page content flashes more than 3 times per second.', 'manual', NULL),
  ('2.3.3', 'Users can disable non-essential animation and movement that is triggered by user interaction', 'manual', NULL),
  ('2.4.1', 'Page content uses landmark regions (ARIA or HTML5 landmarks) to identify major sections of the page.', 'axe-core', 'region'),
  ('2.4.1', 'A visible and operable “skip to main content” (or equivalent) link is provided.', 'manual', NULL),
  ('2.4.1', 'The skip link is keyboard accessible and receives focus when tabbing.', 'manual', NULL),
  ('2.4.1', 'Activating the skip link moves focus past repeated navigation to the main content.', 'manual', NULL),
  ('2.4.1', 'The skip mechanism works consistently across pages with repeated content.', 'manual', NULL),
  ('2.4.1', 'Headings and landmark regions are used logically to support content bypass for assistive technology users.', 'manual', NULL),
  ('2.4.2', 'The document includes a non-empty and present <title> element in the document head.', 'axe-core', 'document-title'),
  ('2.4.2', 'The page title is descriptive and accurately reflects the page’s purpose or content.', 'manual', NULL),
  ('2.4.2', 'The page title is meaningful and informative for users, including screen reader users.', 'manual', NULL),
  ('2.4.2', 'Page titles are unique and distinguishable across different pages of the website or application.', 'manual', NULL),
  ('2.4.2', 'The page title updates appropriately when page content or context changes (e.g., single-page applications).', 'manual', NULL),
  ('2.4.4', 'Links have accessible names that are not empty and are programmatically determinable.', 'axe-core', 'link-name'),
  ('2.4.4', 'Link text or accessible name clearly describes the purpose or destination of the link.', 'manual', NULL),
  ('2.4.4', 'Link purpose can be understood from the link text alone or in combination with surrounding context (such as headings, list items, or table headers).', 'manual', NULL),
  ('2.4.4', 'Links with identical text that point to different destinations are visually and programmatically distinguishable.', 'manual', NULL),
  ('2.4.4', 'Image links and image buttons convey their purpose through meaningful alternative text.', 'manual', NULL),
  ('2.4.4', 'Link purpose remains clear when links are read out of context (e.g., via a screen reader links list).', 'manual', NULL),
  ('2.4.5', 'Multiple ways are available to find other web pages on the site - at least two of: a list of related pages, table of contents, site map, site search, or list of all available web pages.', 'manual', NULL),
  ('2.4.6', 'Heading levels follow a logical and sequential order without skipping levels (e.g., h1 → h2 → h3).', 'axe-core', 'heading-order'),
  ('2.4.6', 'Headings accurately and informatively describe the content or section they introduce.', 'manual', NULL),
  ('2.4.6', 'Form labels and labels for interactive controls clearly describe their purpose.', 'manual', NULL),
  ('2.4.6', 'Duplicate headings or labels are avoided unless context or structure makes their purpose clear.', 'manual', NULL),
  ('2.4.6', 'Headings provide a clear outline and hierarchy that helps users understand page organization.', 'manual', NULL),
  ('2.4.6', 'Headings and labels remain meaningful when accessed out of visual context (e.g., via assistive technology lists).', 'manual', NULL),
  ('2.4.7', 'There is a visible indicator for page elements when they receive keyboard focus.', 'manual', NULL),
  ('2.4.8', 'If a web page is part of a sequence of pages or within a complex site structure, an indication of the current page location is provided, for example, through breadcrumbs or specifying the current step in a sequence (e.g., "Step 2 of 5 - Shipping Address").', 'manual', NULL),
  ('2.4.9', 'Links that have identical accessible names point to the same destination, ensuring that identical link text does not lead to different locations.', 'axe-core', 'identical-links-same-purpose'),
  ('2.4.9', 'Each link’s text alone clearly and accurately describes its purpose without relying on surrounding context.', 'manual', NULL),
  ('2.4.9', 'Image links, image buttons, and image map hotspots have text alternatives that clearly convey their purpose.', 'manual', NULL),
  ('2.4.9', 'Link text is meaningful, descriptive, and not vague (for example, avoiding “click here” or “more”).', 'manual', NULL),
  ('2.4.9', 'Links that appear visually similar but have different purposes are clearly differentiated by their text.', 'manual', NULL),
  ('2.4.9', 'The purpose of links remains clear when presented out of visual context (for example, in a list of links).', 'manual', NULL),
  ('2.4.10', 'Headings follow a logical and hierarchical order without skipping heading levels.', 'axe-core', '- heading-order (partial)'),
  ('2.4.10', 'All meaningful sections of content are identified using headings where appropriate.', 'manual', NULL),
  ('2.4.10', 'Headings accurately describe the content or purpose of their respective sections.', 'manual', NULL),
  ('2.4.10', 'Headings are used consistently to organize content and improve navigability.', 'manual', NULL),
  ('2.4.10', 'Headings are not used solely for visual styling purposes.', 'manual', NULL),
  ('2.4.10', 'Section headings remain meaningful when accessed via assistive technology (e.g., headings list).', 'manual', NULL),
  ('2.5.1', 'If multipoint or path-based gestures (such as pinching, swiping, or dragging across the screen) are not essential to the functionality, then the functionality can also be performed with a single point activation (such as activating a button).', 'manual', NULL),
  ('2.5.2', 'To help avoid inadvertent activation of controls, avoid non-essential down-event (e.g., onmousedown) activation when clicking, tapping, or long pressing the screen.', 'manual', NULL),
  ('2.5.2', 'Use onclick, onmouseup, or similar instead.', 'manual', NULL),
  ('2.5.2', 'If onmouseup (or similar) is used, you must provide a mechanism to abort or undo the action performed.', 'manual', NULL),
  ('2.5.3', 'The accessible name of an interactive component contains the visible text presented to users.', 'axe-core', 'label-content-name-mismatch'),
  ('2.5.3', 'The accessible name includes the visible text in the same order and without altering its meaning.', 'manual', NULL),
  ('2.5.3', 'Accessible names derived from aria-label or aria-labelledby accurately reflect the visible label text.', 'manual', NULL),
  ('2.5.3', 'Image buttons and icons with visible text equivalents include that text in the accessible name.', 'manual', NULL),
  ('2.5.3', 'Dynamic changes to visible labels are reflected in the accessible name.', 'manual', NULL),
  ('2.5.3', 'Abbreviations or symbols used visually are appropriately represented in the accessible name.', 'manual', NULL),
  ('2.5.4', 'Functionality that is triggered by moving the device (such as shaking or panning a mobile device) or by user movement (such as waving to a camera) can be disabled and equivalent functionality is provided via standard controls like buttons.', 'manual', NULL),
  ('2.5.5', 'Clickable targets are at least 44 by 44 pixels in size unless an alternative target of that size is provided, the target is inline (such as a link within a sentence), the target is not author-modified (such as a default checkbox), or the small target size is essential to the functionality.', 'manual', NULL),
  ('2.5.6', 'Content does not require a specific input type, such as touch-only or keyboard-only, but must support alternative inputs (such as using a keyboard on a mobile device).', 'manual', NULL),
  ('3.1.1', 'The <html> element includes a valid and non-empty lang attribute.', 'axe-core', 'html-has-lang, html-lang-valid'),
  ('3.1.1', 'The lang attribute value correctly identifies the primary language of the page content.', 'axe-core', 'html-xml-lang-mismatch'),
  ('3.1.1', 'The language declared in the lang attribute matches the actual language used throughout the page.', 'manual', NULL),
  ('3.1.1', 'The language declaration remains accurate when page content or locale changes dynamically.', 'manual', NULL),
  ('3.1.2', 'Elements with a lang attribute use a valid language code according to BCP', 'axe-core', 'valid-lang'),
  ('3.1.2', '47.', 'manual', NULL),
  ('3.1.2', 'All passages of content written in a different language from the primary page language are correctly identified using the lang attribute.', 'manual', NULL),
  ('3.1.2', 'The language specified in the lang attribute accurately matches the language of the content.', 'manual', NULL),
  ('3.1.2', 'Language changes are applied consistently to all relevant text segments (including dynamically generated content).', 'manual', NULL),
  ('3.1.2', 'Nested language changes are correctly marked when multiple languages appear within the same content block.', 'manual', NULL),
  ('3.1.3', 'Words that may be ambiguous, unfamiliar, or used in a very specific way are defined through adjacent text, a definition list, a glossary, or other suitable method.', 'manual', NULL),
  ('3.1.4', 'The meaning of an unfamiliar abbreviation is provided by expanding it the first time it is used, using the <abbr> element, or linking to a definition or glossary.', 'manual', NULL),
  ('3.1.5', 'A more understandable alternative is provided for content that is more advanced than can be reasonably read by a person with roughly 9 years of primary education.', 'manual', NULL),
  ('3.1.6', 'If the pronunciation of a word is vital to understanding that word, its pronunciation is provided immediately following the word or via a link or glossary', 'manual', NULL),
  ('3.2.1', 'When a page element receives focus, it does not result in a substantial change to the page, the spawning of a pop-up window, an additional change of keyboard focus, or any other change that could confuse or disorient the user.', 'manual', NULL),
  ('3.2.2', 'When a user inputs information or interacts with a control, it does not result in a substantial change to the page, the spawning of a pop-up window, an additional change of keyboard focus, or any other change that could confuse or disorient the user unless the user is informed of the change ahead of time.', 'manual', NULL),
  ('3.2.3', 'Navigation links that are repeated on web pages do not change order when navigating through the site', 'manual', NULL),
  ('3.2.4', 'Elements that have the same functionality across multiple web pages are consistently identified.', 'manual', NULL),
  ('3.2.4', 'For example, a search box at the top of the site should always be labeled the same way.', 'manual', NULL),
  ('3.2.5', 'Substantial changes to the page, the spawning of pop-up windows, uncontrolled changes of keyboard focus, or any other change that could confuse or disorient the user must be initiated by the user.', 'manual', NULL),
  ('3.2.5', 'Alternatively, the user is provided an option to disable such changes.', 'manual', NULL),
  ('3.3.1', 'Required inputs or inputs that require a specific format, value, or length provide this information within the element''s label.', 'manual', NULL),
  ('3.3.1', 'Form validation errors are efficient, intuitive, and accessible.', 'manual', NULL),
  ('3.3.1', 'The error is clearly identified, quick access to the problematic element is provided, and the user can easily fix the error and resubmit the form.', 'manual', NULL),
  ('3.3.2', 'Form controls do not have multiple visible or programmatic labels that would cause confusion for assistive technology users.', 'axe-core', 'form-field-multiple-labels'),
  ('3.3.2', 'Labels or instructions clearly describe the expected input in a way users can easily understand.', 'manual', NULL),
  ('3.3.2', 'Instructions provide sufficient guidance when specific formats, values, or input expectations are required.', 'manual', NULL),
  ('3.3.2', 'Labels or instructions are meaningful, descriptive, and not ambiguous.', 'manual', NULL),
  ('3.3.2', 'Instructions are available to users before input is required.', 'manual', NULL),
  ('3.3.2', 'Visual placement and wording of labels or instructions make the association with the input clear.', 'manual', NULL),
  ('3.3.3', 'If an input error is detected (via client-side or server-side validation), suggestions are provided for fixing the input in a timely and accessible manner.', 'manual', NULL),
  ('3.3.4', 'Submissions, changes, and deletions of legal, financial, or test data can be reversed, verified, or confirmed.', 'manual', NULL),
  ('3.3.5', 'Instructions and cues are provided in context to help in form completion and submission', 'manual', NULL),
  ('3.3.6', 'If the user can submit information, the submission is reversible, verified, or confirmed', 'manual', NULL),
  ('4.1.1', 'Active elements (such as focusable or interactive elements) do not have duplicate id attribute values that could interfere with DOM parsing and assistive technology interaction.', 'axe-core', 'duplicate-id (Deprecated), duplicate-id-active (Deprecated)'),
  ('4.1.1', 'Non-active elements are reviewed to ensure they also do not contain duplicate id values.', 'manual', NULL),
  ('4.1.1', 'Dynamically generated or updated content is checked to confirm duplicate IDs are not introduced after page load.', 'manual', NULL),
  ('4.1.1', 'Overall HTML parsing and markup validity are reviewed to identify other errors that could impact assistive technologies.', 'manual', NULL),
  ('4.1.2', 'Elements with ARIA role attributes use valid, defined ARIA roles that are supported according to the ARIA specification.', 'axe-core', 'aria-hidden-body, aria-roles, aria-valid-attr, aria-valid-attr-value'),
  ('4.1.2', 'Native HTML elements are used wherever possible instead of ARIA roles.', 'axe-core', 'summary-name'),
  ('4.1.2', 'ARIA roles are used only when HTML semantics are insufficient.', 'manual', NULL),
  ('4.1.2', 'The assigned role correctly matches the element’s purpose and behavior.', 'manual', NULL),
  ('4.1.2', 'Required ARIA states and properties for the assigned role are provided.', 'axe-core', 'aria-prohibited-attr'),
  ('4.1.2', 'Accessible names, roles, and values are properly exposed to assistive technologies during interaction.', 'axe-core', 'aria-braille-equivalent, aria-deprecated-role, aria-hidden-focus, aria-input-field-name, aria-required-attr, aria-roledescription  (Deprecated), aria-tooltip-name, frame-title, frame-title-unique, input-image-alt, label'),
  ('4.1.2', 'Custom widgets correctly manage state changes and user interaction feedback.', 'manual', NULL),
  ('4.1.3', 'If an important status message is presented and focus is not set to that message, the message must be announced to screen reader users, typically via an ARIA alert or live region.', 'manual', NULL);
